### ISSUE TITLE
Développement collaboratif avec Github

### ISSUE THREAD

**Issue by iblasquez** [Azalius/ptut#1]
Il y a des outils plus adapté pour discuter que le README ;-)
Regardez les onglets Issues ou Projects et https://github.com/features

**Comment by AurelienTauvy** [comment]
En effet, le README n'est pas un outil adapté pour des discussions au sein du groupe, ce pour quoi je viens de le modifier afin de mieux refléter notre projet.
Nous restons ouverts à tout conseil et toute proposition de possibles améliorations.
